apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: paas-api
  namespace: monitoring
  labels:
    release: kube-prometheus-stack  # must match the Prometheus operator's label selector
spec:
  namespaceSelector:
    matchNames:
      - paas-control-plane
  selector:
    matchLabels:
      app: paas-api  # must match the label on the api-service (i just added it)
  endpoints:
    - port: http
      path: /metrics
      interval: 15s   # scrape every 15 seconds