apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paas-ui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"  # install after API
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yousefkh2/level_3
    targetRevision: main
    path: week_5/manifests
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true