apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paas-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - paas.null.stackit.run
    secretName: paas-tls-cert
  rules:
  - host: paas.null.stackit.run
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: paas-api-service
            port:
              number: 80
      - path: /()(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: paas-ui
            port:
              number: 80