# STAGE 1: build the Go binary

FROM golang:1.25-alpine AS builder

RUN apk add --no-cache git ca-certificates

WORKDIR /build

COPY go.mod go.sum ./

RUN go mod download

COPY . .


RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o api ./main.go



# STAGE 2: minimal runtime image with distroless
FROM gcr.io/distroless/static-debian12:nonroot


COPY --from=builder /build/api /app/api

EXPOSE 8080

# distroless already runs as nonroot user
# K8s probes are better than Docker healthchecks be handled

WORKDIR /app
CMD ["/app/api"]



