apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: paas-control-plane


resources:
  - deployment.yaml
  - hpa.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: paas-api
  app.kubernetes.io/component: control-plane
  app.kubernetes.io/part-of: paas-platform
  app.kubernetes.io/managed-by: argocd

# Common annotations
commonAnnotations:
  managed-by: "ArgoCD"
  week: "4"

# Image transformation (update image tag here for new versions)
images:
  - name: registry.onstackit.cloud/level-3-paas/paas-api
    newTag: git-da65656-20260226103509
